---
- name: "[Darwin] Include {{ ansible_os_family }}-specific variables"
  include_vars: darwin.yml
  tags: pf

- name: '[Darwin] Create /usr/local/bin/firewall.sh script for running PF correctly'
  template:
    src: launchd/firewall.sh.j2
    dest: "/usr/local/bin/firewall.sh"
    owner: root
    group: wheel
    mode: 0755
  become: true
  notify: Reload pfctl
  tags: pf

- name: '[Darwin] Create launchd job for enabling pf at boot'
  template:
    src: launchd/prefix.pf.plist.j2
    dest: "/Library/LaunchDaemons/{{ pf_prefix }}.pf.plist"
    owner: root
    group: wheel
    mode: 0644
  become: true
  notify: Reload pfctl
  tags: pf

- name: '[Darwin] Create launchd job for clearing ssh-bruteforce'
  template:
    src: launchd/prefix.pf.ssh-bruteforce.table-expire.plist.j2
    dest: "/Library/LaunchDaemons/{{ pf_prefix }}.pf.ssh-bruteforce.table-expire.plist"
    owner: root
    group: wheel
    mode: 0644
  become: true
  notify: Reload pf.ssh-bruteforce.table-expire plist
  when: pf_ssh_bruteforce_protect
  tags: pf

- name: '[Darwin] Create launchd job for updating the emerging-threats'
  template:
    src: launchd/prefix.pf.emerging-threats.rules-update.plist.j2
    dest: "/Library/LaunchDaemons/{{ pf_prefix }}.pf.emerging-threats.rules-update.plist"
    owner: root
    group: wheel
    mode: 0644
  become: true
  when: pf_emerging_threats_protect
  notify: Reload pf.emerging-threats.rules-update plist
  tags: pf

# This check is required unconditionally.
# Even if no files were changed, pf can still be disabled, so we should enable it in this case.
- name: '[Darwin] Check if {{ pf_prefix }} launchd jobs are loaded (yellow if not)'
  shell: launchctl list | grep {{ pf_prefix }}
  become: true
  register: pf_launchd_job
  failed_when: false
  changed_when: pf_launchd_job.rc == 1  # trigger the 'Load pfctl' handler if job is not loaded
  notify:
    - Reload pf.ssh-bruteforce.table-expire plist
    - Reload pf.emerging-threats.rules-update plist
    - Reload pfctl
